// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpQnk7Go5l4sh7Su8qA6v-wQg8WQ-OPhI',
    appId: '1:591867621340:web:69ec7629e67b6c6985e919',
    messagingSenderId: '591867621340',
    projectId: 'toolshare-58445',
    authDomain: 'toolshare-58445.firebaseapp.com',
    storageBucket: 'toolshare-58445.firebasestorage.app',
    measurementId: 'G-TJR1RD15TX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx72Yy5Ob2-9RYbUr0jqoaho0wv5VNHbs',
    appId: '1:591867621340:android:35cf2097e8bc249585e919',
    messagingSenderId: '591867621340',
    projectId: 'toolshare-58445',
    storageBucket: 'toolshare-58445.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbSoWgWzsOUQ3NlWcCxJH9Zh_aWUE4zmI',
    appId: '1:591867621340:ios:ed3a527f3269853685e919',
    messagingSenderId: '591867621340',
    projectId: 'toolshare-58445',
    storageBucket: 'toolshare-58445.firebasestorage.app',
    iosBundleId: 'com.example.toolshare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbSoWgWzsOUQ3NlWcCxJH9Zh_aWUE4zmI',
    appId: '1:591867621340:ios:ed3a527f3269853685e919',
    messagingSenderId: '591867621340',
    projectId: 'toolshare-58445',
    storageBucket: 'toolshare-58445.firebasestorage.app',
    iosBundleId: 'com.example.toolshare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpQnk7Go5l4sh7Su8qA6v-wQg8WQ-OPhI',
    appId: '1:591867621340:web:00ca93e9847b34e185e919',
    messagingSenderId: '591867621340',
    projectId: 'toolshare-58445',
    authDomain: 'toolshare-58445.firebaseapp.com',
    storageBucket: 'toolshare-58445.firebasestorage.app',
    measurementId: 'G-GZ94F7V2WE',
  );
}
